### ISSUE TITLE
Fix list

### ISSUE THREAD

**Issue by Bellfalasch** [okajimo/EWW#1]
Hi, the app needs the following fixes:

* Weather is fetched only once (on load) and then never again. It should fetch every 60 seconds.
* Remove PHP-dependency, it is used only to include to include files with minimal code on a single page app. Adds bloat to the app.
* Refactor the CSS used `custom.css` in such a way that there is no need for all those nasty  `!important`-hacks.
* Create a readme.md in root and add the instructions to it instead of delivered through a separate PDF-file.

**Comment by okajimo** [comment]
Done :)
